# Site settings
language:               ""
title:                  "Site Title"
description:            "Site description"
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

# keep in mind that jekyll is going to exclude this files in jekyll build task from gulp.
exclude:
  - "assets/js/lib/"
  - "assets/scss/"
  - "assets/js/app.js"
  - "composer.json"
  - "composer.lock"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "yarn-error.log"
  - "gulpfile.js"

# if there are extra generated files (such as bundle.js from webpack or minified app.cs) we have to let
# jekyll know about it, otherwise it will delete them
keep_files:
  - "assets/js/bundle.js"
  - "assets/css/app.css"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge
